version: '3.8'

services:
  api:
    build: .
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - GIN_MODE=release
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - CACHE_TTL=600
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: price-comparison-network
